// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rftzgqqqbfgjdbywbaha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmdHpncXFxYmZnamRieXdiYWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NjQzODgsImV4cCI6MjA4ODU0MDM4OH0.cExASJYFclk4YXG_PWPV9gP0Bf9QjngzzwqQfKRuSlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});